blue:
  hmax: 124
  hmin: 90
  smax: 255
  smin: 224
  vmax: 195
  vmin: 120
green:
  hmax: 85
  hmin: 50
  smax: 225
  smin: 135
  vmax: 200
  vmin: 130
white:
  hmax: 115
  hmin: 70
  smax: 50
  smin: 0
  vmax: 150
  vmin: 90
yellow:
  hmax: 50
  hmin: 20
  smax: 255
  smin: 147
  vmax: 255
  vmin: 170
orange:
  hmax: 16
  hmin: 0
  smax: 255
  smin: 180
  vmax: 255
  vmin: 190
image:
  ROI_height: 480
  ROI_wdith: 640
  ROI_x: 0
  ROI_y: 0
red:
  hmax: 10
  hmin: 0
  smax: 255
  smin: 175
  vmax: 190
  vmin: 100
